### ISSUE TITLE
[BUG] The share link functionallity does not restore the shader at all

### ISSUE THREAD

**Issue by Mathias-Boulay** [zeokku/glsl.app#21]
Hi there, first of all thank you for the playground you provided to the world.

I intend to make a short introduction to fragment shaders, and I would like to provide snippets the students could play around with.
Unfortunately, the links generated by the share button do not load the shader inside any tab loading it.

Example:  [link to a basic shader](https://glsl.app/#~epqhd4iyyfb4ngbo4y2rsb9p)
The glsl file does not get downloaded.
Network screenshot from a clean load of the webpage with the link from the example:
![image](https://github.com/zeokku/glsl.app/assets/24864674/91265f70-d3e5-41b4-a2f1-32857fe9b258)

![image](https://github.com/zeokku/glsl.app/assets/24864674/59724d58-f0d5-46d6-bcbb-df14c3a8a80f)

**Side Note**: When watching the console, it seems that the index.html file does not get delivered. Seems unrelated to our issue though.

**Comment by Lutymane** [comment]
Thank you for reporting the issue!

I have pushed a fix (it was caused because I forgot to regenerate GraphQL code for the latest update), make sure to force reload the page (it should say `build 08/02/24` in console)

**Comment by Mathias-Boulay** [comment]
I'll try it out right away !

**Comment by Mathias-Boulay** [comment]
The texture doesn't load but it's normal that it isn't stored on the server. Thanks !
