### ISSUE TITLE
I think the DB in production shut down

### ISSUE THREAD

**Issue by Mathias-Boulay** [zeokku/glsl.app#22]
Hey there, I'm back again :sweat_smile: 

![image](https://github.com/zeokku/glsl.app/assets/24864674/0b819f19-44a7-41f4-8796-eb4a62ba4621)

```json
{"errors":[{"message":"org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction","locations":[],"path":["shader"],"extensions":{"errorType":"INTERNAL"}}],"data":{"shader":null}}
```

I think your DB is down :eyes:

**Comment by etareduction** [comment]
> I think your DB is down 👀

It was a disk space problem on a server. Now fixed.

**Comment by Mathias-Boulay** [comment]
This makes me wonder how long any link lasts before the shader gets deleted ?

**Comment by etareduction** [comment]
> This makes me wonder how long any link lasts before the shader gets deleted ?

The shaders themselves are very tiny in practice, i haven't cleared the shader database itself and with our current traffic i don't think i would have to in a long time. The reason for this incident was my log rotation not working. So just a couple 50 gig log files polluted the entire disk space. It seems like log rotation works now.

**Comment by Mathias-Boulay** [comment]
waou that's a big log !
I guess I'll close the issue then :smile: Thanks again
